apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-app
  template:
    metadata:
      labels:
        app: grpc-app
    spec:
      containers:
        - name: grpc-app
          image: mydesiredcontainerregistryname.azurecr.io/grpc-app:tag
          ports:
            - containerPort: 8090
      imagePullSecrets:
        - name: mydesiredcontainerregistryname-cred